In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('phpvcoG8S.csv', encoding='utf-8')

In [2]:
df

       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0           CO     269         SFO       IAH          3    15     205      1
1           US    1558         PHX       CLT          3    15     222      1
2           AA    2400         LAX       DFW          3    20     165      1
3           AA    2466         SFO       DFW          3    20     195      1
4           AS     108         ANC       SEA          3    30     202      0
5           CO    1094         LAX       IAH          3    30     181      1
6           DL    1768         LAX       MSP          3    30     220      0
7           DL    2722         PHX       DTW          3    30     228      0
8           DL    2606         SFO       MSP          3    35     216      1
9           AA    2538         LAS       ORD          3    40     200      1
10          CO     223         ANC       SEA          3    49     201      1
11          DL    1646         PHX       ATL          3    50     212      1
12          DL    2055         SLC       ATL          3    50     210      0
13          AA    2408         LAX       DFW          3    55     170      0
14          AS     132         ANC       PDX          3    55     215      0
15          US     498         DEN       CLT          3    55     179      0
16          B6      98         DEN       JFK          3    59     213      0
17          CO    1496         LAS       IAH          3    60     162      0
18          DL    1450         LAS       MSP          3    60     181      0
19          CO     507         ONT       IAH          3    75     167      0
20          AS     128         FAI       SEA          3    80     206      0
21          DL    2223         ANC       SLC          3    85     270      0
22          AS     112         ANC       SEA          3    90     200      0
23          HA      17         LAS       HNL          3   100     380      1
24          US     122         ANC       PHX          3   113     327      1
25          AS     114         ANC       SEA          3   150     200      0
26          B6     766         BQN       MCO          3   240     169      0
27          B6     768         PSE       MCO          3   262     180      0
28          HA     206         HNL       OGG          3   300      36      1
29          OO    4746         BIS       MSP          3   300      85      0
...        ...     ...         ...       ...        ...   ...     ...    ...
539353      US      31         OGG       PHX          5  1410     344      0
539354      B6     767         MCO       PSE          5  1413     160      1
539355      DL    1930         LAX       CVG          5  1415     248      1
539356      UA      92         OGG       DEN          5  1416     404      0
539357      CO     434         PHX       EWR          5  1420     259      1
539358      B6     172         SMF       JFK          5  1424     308      0
539359      AA      30         LAX       JFK          5  1425     314      1
539360      B6    1761         FLL       SJU          5  1425     144      1
539361      B6     723         JFK       BQN          5  1425     216      1
539362      B6     749         MCO       SJU          5  1425     154      0
539363      DL    1002         SLC       JFK          5  1425     264      1
539364      FL     225         LAS       MKE          5  1425     208      0
539365      US     119         KOA       PHX          5  1425     349      1
539366      US     258         PHX       PHL          5  1425     254      0
539367      UA      86         HNL       LAX          5  1428     333      0
539368      CO     208         PDX       IAH          5  1430     227      0
539369      US     125         HNL       PHX          5  1430     362      0
539370      AA    1488         DEN       MIA          5  1435     220      1
539371      AA    1522         SFO       ORD          5  1435     240      0
539372      AA     238         LAX       SJU          5  1435     390      0
539373      B6     480         LAX       BOS          5  1435     320      1
539374      DL    2354         LAX       ATL          5  1435     255      0
539375      FL      58         LAX       ATL          5  1435     250      0
539376      B6     717         JFK       SJU          5  1439     220      1
539377      B6     739         JFK       PSE          5  1439     223      1
539378      CO     178         OGG       SNA          5  1439     326      0
539379      FL     398         SEA       ATL          5  1439     305      0
539380      FL     609         SFO       MKE          5  1439     255      0
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1

[539383 rows x 8 columns]

In [3]:
x = df.iloc[:,0:7]
y = df.iloc[:,7:]

In [4]:
x

       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length
0           CO     269         SFO       IAH          3    15     205
1           US    1558         PHX       CLT          3    15     222
2           AA    2400         LAX       DFW          3    20     165
3           AA    2466         SFO       DFW          3    20     195
4           AS     108         ANC       SEA          3    30     202
5           CO    1094         LAX       IAH          3    30     181
6           DL    1768         LAX       MSP          3    30     220
7           DL    2722         PHX       DTW          3    30     228
8           DL    2606         SFO       MSP          3    35     216
9           AA    2538         LAS       ORD          3    40     200
10          CO     223         ANC       SEA          3    49     201
11          DL    1646         PHX       ATL          3    50     212
12          DL    2055         SLC       ATL          3    50     210
13          AA    2408         LAX       DFW          3    55     170
14          AS     132         ANC       PDX          3    55     215
15          US     498         DEN       CLT          3    55     179
16          B6      98         DEN       JFK          3    59     213
17          CO    1496         LAS       IAH          3    60     162
18          DL    1450         LAS       MSP          3    60     181
19          CO     507         ONT       IAH          3    75     167
20          AS     128         FAI       SEA          3    80     206
21          DL    2223         ANC       SLC          3    85     270
22          AS     112         ANC       SEA          3    90     200
23          HA      17         LAS       HNL          3   100     380
24          US     122         ANC       PHX          3   113     327
25          AS     114         ANC       SEA          3   150     200
26          B6     766         BQN       MCO          3   240     169
27          B6     768         PSE       MCO          3   262     180
28          HA     206         HNL       OGG          3   300      36
29          OO    4746         BIS       MSP          3   300      85
...        ...     ...         ...       ...        ...   ...     ...
539353      US      31         OGG       PHX          5  1410     344
539354      B6     767         MCO       PSE          5  1413     160
539355      DL    1930         LAX       CVG          5  1415     248
539356      UA      92         OGG       DEN          5  1416     404
539357      CO     434         PHX       EWR          5  1420     259
539358      B6     172         SMF       JFK          5  1424     308
539359      AA      30         LAX       JFK          5  1425     314
539360      B6    1761         FLL       SJU          5  1425     144
539361      B6     723         JFK       BQN          5  1425     216
539362      B6     749         MCO       SJU          5  1425     154
539363      DL    1002         SLC       JFK          5  1425     264
539364      FL     225         LAS       MKE          5  1425     208
539365      US     119         KOA       PHX          5  1425     349
539366      US     258         PHX       PHL          5  1425     254
539367      UA      86         HNL       LAX          5  1428     333
539368      CO     208         PDX       IAH          5  1430     227
539369      US     125         HNL       PHX          5  1430     362
539370      AA    1488         DEN       MIA          5  1435     220
539371      AA    1522         SFO       ORD          5  1435     240
539372      AA     238         LAX       SJU          5  1435     390
539373      B6     480         LAX       BOS          5  1435     320
539374      DL    2354         LAX       ATL          5  1435     255
539375      FL      58         LAX       ATL          5  1435     250
539376      B6     717         JFK       SJU          5  1439     220
539377      B6     739         JFK       PSE          5  1439     223
539378      CO     178         OGG       SNA          5  1439     326
539379      FL     398         SEA       ATL          5  1439     305
539380      FL     609         SFO       MKE          5  1439     255
539381      UA      78         HNL       SFO          5  1439     313
539382      US    1442         LAX       PHL          5  1439     301

[539383 rows x 7 columns]

In [5]:
y

        Delay
0           1
1           1
2           1
3           1
4           0
5           1
6           0
7           0
8           1
9           1
10          1
11          1
12          0
13          0
14          0
15          0
16          0
17          0
18          0
19          0
20          0
21          0
22          0
23          1
24          1
25          0
26          0
27          0
28          1
29          0
...       ...
539353      0
539354      1
539355      1
539356      0
539357      1
539358      0
539359      1
539360      1
539361      1
539362      0
539363      1
539364      0
539365      1
539366      0
539367      0
539368      0
539369      0
539370      1
539371      0
539372      0
539373      1
539374      0
539375      0
539376      1
539377      1
539378      0
539379      0
539380      0
539381      1
539382      1

[539383 rows x 1 columns]

In [7]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [9]:
labelencoder_X = LabelEncoder()
df[:,3] = labelencoder_X.fit_transform(df[:,3])

TypeError: unhashable type: 'slice'

In [17]:
X = df.iloc[:,:].values
Z=pd.DataFrame(X)

In [21]:
X[:,3] = labelencoder_X.fit_transform(X[:,3])
X[:,0] = labelencoder_X.fit_transform(X[:,0])
X[:,2] = labelencoder_X.fit_transform(X[:,2])

In [22]:
Z

         0     1    2    3  4     5    6  7
0        4   269  253  135  3    15  205  1
1       14  1558  217   60  3    15  222  1
2        1  2400  154   80  3    20  165  1
3        1  2466  253   80  3    20  195  1
4        2   108   14  252  3    30  202  0
5        4  1094  154  135  3    30  181  1
6        5  1768  154  197  3    30  220  0
7        5  2722  217   85  3    30  228  0
8        5  2606  253  197  3    35  216  1
9        1  2538  153  208  3    40  200  1
10       4   223   14  252  3    49  201  1
11       5  1646  217   16  3    50  212  1
12       5  2055  261   16  3    50  210  0
13       1  2408  154   80  3    55  170  0
14       2   132   14  214  3    55  215  0
15      14   498   79   60  3    55  179  0
16       3    98   79  148  3    59  213  0
17       4  1496  153  135  3    60  162  0
18       5  1450  153  197  3    60  181  0
19       4   507  207  135  3    75  167  0
20       2   128   98  252  3    80  206  0
21       5  2223   14  261  3    85  270  0
22       2   112   14  252  3    90  200  0
23       9    17  153  128  3   100  380  1
24      14   122   14  217  3   113  327  1
25       2   114   14  252  3   150  200  0
26       3   766   37  173  3   240  169  0
27       3   768  225  173  3   262  180  0
28       9   206  128  203  3   300   36  1
29      12  4746   29  197  3   300   85  0
...     ..   ...  ...  ... ..   ...  ... ..
539353  14    31  203  217  5  1410  344  0
539354   3   767  173  225  5  1413  160  1
539355   5  1930  154   71  5  1415  248  1
539356  13    92  203   79  5  1416  404  0
539357   4   434  217   96  5  1420  259  1
539358   3   172  262  148  5  1424  308  0
539359   1    30  154  148  5  1425  314  1
539360   3  1761  104  260  5  1425  144  1
539361   3   723  148   37  5  1425  216  1
539362   3   749  173  260  5  1425  154  0
539363   5  1002  261  148  5  1425  264  1
539364   8   225  153  184  5  1425  208  0
539365  14   119  150  217  5  1425  349  1
539366  14   258  217  216  5  1425  254  0
539367  13    86  128  154  5  1428  333  0
539368   4   208  214  135  5  1430  227  0
539369  14   125  128  217  5  1430  362  0
539370   1  1488   79  183  5  1435  220  1
539371   1  1522  253  208  5  1435  240  0
539372   1   238  154  260  5  1435  390  0
539373   3   480  154   35  5  1435  320  1
539374   5  2354  154   16  5  1435  255  0
539375   8    58  154   16  5  1435  250  0
539376   3   717  148  260  5  1439  220  1
539377   3   739  148  225  5  1439  223  1
539378   4   178  203  264  5  1439  326  0
539379   8   398  252   16  5  1439  305  0
539380   8   609  253  184  5  1439  255  0
539381  13    78  128  253  5  1439  313  1
539382  14  1442  154  216  5  1439  301  1

[539383 rows x 8 columns]

In [25]:
x = Z.iloc[:,0:7]
y = Z.iloc[:,7:]

In [26]:
x

         0     1    2    3  4     5    6
0        4   269  253  135  3    15  205
1       14  1558  217   60  3    15  222
2        1  2400  154   80  3    20  165
3        1  2466  253   80  3    20  195
4        2   108   14  252  3    30  202
5        4  1094  154  135  3    30  181
6        5  1768  154  197  3    30  220
7        5  2722  217   85  3    30  228
8        5  2606  253  197  3    35  216
9        1  2538  153  208  3    40  200
10       4   223   14  252  3    49  201
11       5  1646  217   16  3    50  212
12       5  2055  261   16  3    50  210
13       1  2408  154   80  3    55  170
14       2   132   14  214  3    55  215
15      14   498   79   60  3    55  179
16       3    98   79  148  3    59  213
17       4  1496  153  135  3    60  162
18       5  1450  153  197  3    60  181
19       4   507  207  135  3    75  167
20       2   128   98  252  3    80  206
21       5  2223   14  261  3    85  270
22       2   112   14  252  3    90  200
23       9    17  153  128  3   100  380
24      14   122   14  217  3   113  327
25       2   114   14  252  3   150  200
26       3   766   37  173  3   240  169
27       3   768  225  173  3   262  180
28       9   206  128  203  3   300   36
29      12  4746   29  197  3   300   85
...     ..   ...  ...  ... ..   ...  ...
539353  14    31  203  217  5  1410  344
539354   3   767  173  225  5  1413  160
539355   5  1930  154   71  5  1415  248
539356  13    92  203   79  5  1416  404
539357   4   434  217   96  5  1420  259
539358   3   172  262  148  5  1424  308
539359   1    30  154  148  5  1425  314
539360   3  1761  104  260  5  1425  144
539361   3   723  148   37  5  1425  216
539362   3   749  173  260  5  1425  154
539363   5  1002  261  148  5  1425  264
539364   8   225  153  184  5  1425  208
539365  14   119  150  217  5  1425  349
539366  14   258  217  216  5  1425  254
539367  13    86  128  154  5  1428  333
539368   4   208  214  135  5  1430  227
539369  14   125  128  217  5  1430  362
539370   1  1488   79  183  5  1435  220
539371   1  1522  253  208  5  1435  240
539372   1   238  154  260  5  1435  390
539373   3   480  154   35  5  1435  320
539374   5  2354  154   16  5  1435  255
539375   8    58  154   16  5  1435  250
539376   3   717  148  260  5  1439  220
539377   3   739  148  225  5  1439  223
539378   4   178  203  264  5  1439  326
539379   8   398  252   16  5  1439  305
539380   8   609  253  184  5  1439  255
539381  13    78  128  253  5  1439  313
539382  14  1442  154  216  5  1439  301

[539383 rows x 7 columns]

In [27]:
y

        7
0       1
1       1
2       1
3       1
4       0
5       1
6       0
7       0
8       1
9       1
10      1
11      1
12      0
13      0
14      0
15      0
16      0
17      0
18      0
19      0
20      0
21      0
22      0
23      1
24      1
25      0
26      0
27      0
28      1
29      0
...    ..
539353  0
539354  1
539355  1
539356  0
539357  1
539358  0
539359  1
539360  1
539361  1
539362  0
539363  1
539364  0
539365  1
539366  0
539367  0
539368  0
539369  0
539370  1
539371  0
539372  0
539373  1
539374  0
539375  0
539376  1
539377  1
539378  0
539379  0
539380  0
539381  1
539382  1

[539383 rows x 1 columns]

In [36]:
onehotencoder = OneHotEncoder(categorical_features=[3])

In [37]:
x=onehotencoder.fit_transform(x).toarray()

In [38]:
x

array([[   0.,    0.,    0., ...,    3.,   15.,  205.],
       [   0.,    0.,    0., ...,    3.,   15.,  222.],
       [   0.,    0.,    0., ...,    3.,   20.,  165.],
       ...,
       [   0.,    0.,    0., ...,    5., 1439.,  255.],
       [   0.,    0.,    0., ...,    5., 1439.,  313.],
       [   0.,    0.,    0., ...,    5., 1439.,  301.]])

In [28]:
from sklearn.cross_validation import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.1,random_state = 100)

c:\users\sanchit goel\appdata\local\programs\python\python36\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [29]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(x_train,y_train)

c:\users\sanchit goel\appdata\local\programs\python\python36\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: Unknown label type: 'unknown'